[09/10/2017 16:30] ERROR red on_command_error 369: Exception in command 'welcomeset'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/fluff/cogs/welcome.py", line 33, in welcomeset
    self.settings[server.id]["CHANNEL"] = server.default_channel.id
AttributeError: 'NoneType' object has no attribute 'id'
[10/10/2017 05:17] ERROR red on_command_error 369: Exception in command 'speak'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/fluff/cogs/blah.py", line 28, in speak
    channel = ctx.message.channel_mentions[0]
IndexError: list index out of range
[11/10/2017 03:46] ERROR red load_cogs 573: ffmpeg isn't installed.
Consult the guide for your operating system and do ALL the steps in order.
https://twentysix26.github.io/Red-Docs/
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\murra\fluff\cogs\owner.py", line 947, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "C:\Users\murra\fluff\cogs\audio.py", line 2378, in setup
    "".format(msg))
RuntimeError: ffmpeg isn't installed.
Consult the guide for your operating system and do ALL the steps in order.
https://twentysix26.github.io/Red-Docs/

[11/10/2017 03:46] ERROR red load_cogs 573: Can't load pymongo. Do 'pip3 install pymongo'.
Traceback (most recent call last):
  File "C:\Users\murra\fluff\cogs\leveler.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\murra\fluff\cogs\owner.py", line 945, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\murra\fluff\cogs\leveler.py", line 14, in <module>
    raise RuntimeError("Can't load pymongo. Do 'pip3 install pymongo'.")
RuntimeError: Can't load pymongo. Do 'pip3 install pymongo'.
